// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibrarySource } from "./LibrarySource";
import type { LyricsPosition } from "./LyricsPosition";

export type AppConfig = {
  data_path: string | null;
  /**
   * Deprecated. Kept for one-shot migration into `library_source`; never
   * written by code that has been through `with_defaults`.
   */
  last_folder: string | null;
  library_source: LibrarySource | null;
  last_theme: number | null;
  guide_volume: number | null;
  fullscreen: boolean | null;
  dark_mode: boolean | null;
  mic_active: boolean | null;
  /**
   * `serde(alias = "mic_mirroring")` keeps configs written by builds that
   * called this feature "mic mirroring" loading without a manual migration;
   * the next `save` rewrites them under the new name.
   */
  mic_monitoring: boolean | null;
  mic_monitor_gain: number | null;
  preferred_mic: string | null;
  whisper_model: string | null;
  beam_size: number | null;
  batch_size: number | null;
  last_video_flavor: number | null;
  separator: string | null;
  asr_engine: string | null;
  language_overrides: { [key in string]: string } | null;
  /**
   * Vertical anchor for lyrics during playback (top / center / bottom).
   */
  lyrics_position: LyricsPosition | null;
  /**
   * Multiplier applied to the lyrics font size; `1.0` is the default size.
   */
  lyrics_font_scale: number | null;
};
