// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibrarySource } from "./LibrarySource";
import type { LyricsPosition } from "./LyricsPosition";

export type AppConfig = {
  data_path: string | null;
  /**
   * Deprecated. Kept for one-shot migration into `library_source`; never
   * written by code that has been through `with_defaults`.
   */
  last_folder: string | null;
  library_source: LibrarySource | null;
  last_theme: number | null;
  guide_volume: number | null;
  fullscreen: boolean | null;
  dark_mode: boolean | null;
  mic_active: boolean | null;
  /**
   * `serde(alias = "mic_mirroring")` keeps configs written by builds that
   * called this feature "mic mirroring" loading without a manual migration;
   * the next `save` rewrites them under the new name.
   */
  mic_monitoring: boolean | null;
  mic_monitor_gain: number | null;
  preferred_mic: string | null;
  whisper_model: string | null;
  beam_size: number | null;
  batch_size: number | null;
  last_video_flavor: number | null;
  separator: string | null;
  asr_engine: string | null;
  language_overrides: { [key in string]: string } | null;
  /**
   * Enables host/guest karaoke session mode in the web UI.
   */
  karaoke_enabled: boolean | null;
  /**
   * Join code guests must enter on their phones.
   */
  karaoke_pin: string | null;
  /**
   * Default display name for the host controller.
   */
  karaoke_display_name: string | null;
  /**
   * Whether non-host guests can use playback/settings/admin controls.
   */
  karaoke_allow_guest_controls: boolean | null;
  /**
   * Base URL for the local Downtify instance used by "Request Song".
   */
  downtify_base_url: string | null;
  /**
   * Periodically trigger a background library rescan. `null`/`0` disables it.
   */
  auto_rescan_seconds: number | null;
  /**
   * Automatically enqueue newly discovered songs/videos for analysis after scans.
   */
  auto_analyze_new_content: boolean | null;
  /**
   * Vertical anchor for lyrics during playback (top / center / bottom).
   */
  lyrics_position: LyricsPosition | null;
  /**
   * Multiplier applied to the lyrics font size; `1.0` is the default size.
   */
  lyrics_font_scale: number | null;
  /**
   * Reduce visual rendering cost on low-power devices.
   */
  playback_performance_mode: boolean | null;
  /**
   * Show the pitch graph overlay during playback.
   */
  playback_show_pitch_graph: boolean | null;
  /**
   * Audio decode strategy for playback: `client_mp3` (default) or `server_pcm`.
   */
  playback_audio_decode_mode: string | null;
  /**
   * Enable host-side queue prewarm decode cache for faster transitions.
   */
  playback_warmup_cache_enabled: boolean | null;
  /**
   * Keep a small sticky in-memory predecode buffer for smoother transitions.
   */
  playback_sticky_predecode: boolean | null;
  /**
   * Start playback after instrumental decode and attach vocals when ready.
   */
  playback_fast_start_instrumental_first: boolean | null;
};
